Update Okta Module to use Models
cartography-cncf/cartography pull request #1243
Opened 2023-09-19 19:34 UTC by csanders-git

2023-10-19 18:45 UTC, achantavy requested changes, later dismissed
Thanks for taking on the data model refactor and using the new Okta async APIs (and getting rid of a long-standing "miss last page" bug).

I gave this a first pass and my main blockers are:

1. Getting rid of awssaml - we need to keep this.
2. Okta group role transform efficiency: the list of group roles can be huge so there is a lot of wasted work here. Let's come up with a faster and cleaner way of doing this.

Since this is a big PR, we might need a few rounds. In future for faster merging it'd be better to make refactors true refactors with no new added functionality.

2023-10-19 18:45 UTC, achantavy commented on cartography/models/okta/application.py
> +    # TODO: Find out when this is used
Nit: Can we remove the TODO here and replace it with a GitHub issue instead?

2023-10-19 18:45 UTC, achantavy commented on cartography/models/okta/application.py
> +    # TODO: Figure out profile
Nit: TODOs to GH issues.

2023-10-19 18:45 UTC, achantavy commented on cartography/models/okta/application.py
> +    # settings_oauth_client_jwks: PropertyRef = PropertyRef("settings_oauth_client_jwks")
Let's clean this up

2023-10-19 18:45 UTC, achantavy commented on cartography/models/okta/application.py
> +    # settings_oauth_client_refresh_token: PropertyRef = PropertyRef(
Let's clean this up

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/origins.py
> +            string_value = None
`string_value` is never set. Can we delete this line and delete these lines too?

```python
origin_props["cors_value"] = string_value
...
origin_props["redirect_value"] = string_value
...
origin_props["iframe_value"] = string_value
```

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/groups.py
> +        # TODO: It is probably possible to create a more advanced rule via API
TODOs -> tickets

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/groups.py
> +    :param okta_group_roles: List of Okta group roles
The datatype is OktaGroup. Double checking but is this comment correct?

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/groups.py
> +def sync_okta_groups(
This function syncs group roles, groups, and then group rules. It isn't nested deeply so I think it'd be straightforward to split to 3 different functions: sync_group_roles(), sync_groups(), and sync_group_rules(). I think the end result will be easier to read.

Also, is the ordering correct -- should we instead make it groups, then group roles, then group rules?

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/groups.py
> +        # TODO: Converting this into a hashmap would make perform better
This feels like _a lot_ of wasted work since the group-role list can be very big. Let's take some time to think about restructuring.

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/authenticators.py
> +# TODO: Authenticator's enrolled per user
Let's clean this up

2023-10-19 18:45 UTC, achantavy commented on cartography/intel/okta/__init__.py
> +    # TODO: Deprecate this while we determine a method of making it more generic
Blocker: This is still needed.

2023-10-19 22:09 UTC, achantavy commented on cartography/intel/okta/groups.py
> +def sync_okta_groups(
Update: This is a nonblocker.

2026-01-30 19:29 UTC, jychp commented on cartography/intel/okta/organization.py
> +def sync_okta_organization(
acceptable for tenants

2026-02-03 21:48 UTC, jychp commented
This PR is not working and blocked by: https://github.com/okta/okta-sdk-python/issues/481

2026-04-18 15:58 UTC, jychp commented
@cubic-dev-ai review this PR again

2026-04-18 16:02 UTC, jychp commented on cartography/data/indexes.cypher
On doit pouvoir supprimer les autres index sur Okta non ?

2026-04-22 16:20 UTC, jychp commented on cartography/intel/okta/applications.py
>  # Okta intel module - Applications
supprimme ce commentaire inutile

2026-04-22 16:38 UTC, jychp commented on cartography/intel/okta/groups.py
> +    except OktaApiError as exc:
Intentional — E0000006 soft-fail lets syncs continue when the API token lacks super-admin; same pattern in users.py:167.

2026-04-22 16:39 UTC, jychp commented on cartography/intel/okta/authenticators.py
> +    return authenticators or []
Graceful empty-result handling — the SDK error path is already raised via raise_for_okta_error; the fallback only covers a None-data/no-error response.

2026-04-22 20:36 UTC, jychp commented
Now blocked by: https://github.com/okta/okta-sdk-python/issues/536

2026-08-20 05:57 UTC, jasonhernandez commented
Status update on the upstream blocker, since both issues this PR was waiting on are now closed but the underlying problem is not resolved.

- okta/okta-sdk-python#481 (Pydantic rejects valid empty strings) — closed 2026-04-09, genuinely fixed.
- okta/okta-sdk-python#536 (`list_applications` fails on SAML apps omitting required `signOn` fields) — closed 2026-05-12, "fixed" in v3.4.3. **The fix was partial**: it relaxed the ten `StrictStr` fields and left all five `StrictBool` fields required (`allowMultipleAcsEndpoints`, `assertionSigned`, `honorForceAuthn`, `requestCompressed`, `responseSigned`). `SamlApplicationSettingsSignOn.model_fields` reports 15 required fields on 3.4.2 and exactly those 5 on both 3.4.3 and 3.4.4.

I measured 3.4.4 against a production tenant (50 SAML apps, `filter=signOnMode eq "SAML_2_0"`), feeding each app individually into `ApplicationJsonConverter.from_dict`:

| | count |
|---|---|
| SAML apps returned | 50 |
| Fail to deserialize | **39 (78%)** |
| Deserialize cleanly | 11 |

Since `api_client.py::__deserialize` validates a page in one list comprehension, `list_applications` returns `None` for all 50.

The failures resolve into three distinct defects, not one:

1. The residual #536 booleans — 33 apps. Worth noting the framing in #536 was too narrow: these are **OIN catalog apps** (`salesforce`, `slack`, `google`, `amazon_aws_sso`, and 25 other templates), whose `settings.signOn` uses the `*Override` shape because the SAML mechanics live in the catalog template. Every app with the full custom-SAML shape validated fine. So this affects any tenant using OIN SAML integrations, not just unusually configured ones.
2. `Application.features` enum is missing `AUTO_CONFIRM_IMPORTS`, which Okta returns for custom SAML apps with SCIM provisioning — 5 apps. Separate mechanism (incomplete enum, not an over-strict required field).
3. `BrowserPluginApplication.name` is constrained to `('template_swa', 'template_swa3field')`, so OIN catalog SWA apps cannot deserialize — 1 app in the filtered set. This one shows the problem is not SAML-specific, so an unfiltered sync would likely hit further sign-on modes.

Filed upstream as okta/okta-sdk-python#574 with a credential-free reproduction for all three.

Practical implication for this PR: bumping to `okta>=3.4.0` is not sufficient on its own — defects 1 and 2 both have to land before the Okta module can enumerate applications in a tenant like this, and defect 3 likely matters too. Happy to test a rebase against a real tenant once upstream moves.

Also flagging that this PR was marked stale on 2026-07-22 and is at risk of auto-closing.

2026-08-29 22:24 UTC, kunaals commented
@jasonhernandez thanks for pointing that out, we’ve added temporary shims for the SDK issues and escalated them with okta support (just got off a call with them). we’ll remove the shims once the SDK is fixed, but they shouldn’t block these improvements or the observability we need from the okta module

2026-08-29 22:25 UTC, kunaals commented
@achantavy i tried closing and re-opening and there is still a license failure, mind taking a look?

2026-08-30 01:12 UTC, achantavy commented
kicked fossa. closing and then reopening

2026-08-30 01:34 UTC, achantavy approved these changes
We are merging this PR before it hits its 3rd birthday woohoo

2026-08-30 01:41 UTC, merged